#!/bin/bash
find -L static > filelist.tmp
find -L templates >> filelist.tmp
find -L resources | grep 'py$' >> filelist.tmp
find -L database | grep 'py$' >> filelist.tmp
find -L searchengine | grep 'py$' >> filelist.tmp
echo "app.py" >> filelist.tmp
echo "__init__.py" >> filelist.tmp
echo "reverseproxy.py" >> filelist.tmp
echo "restnames.wsgi" >> filelist.tmp
echo "APIlayout" >> filelist.tmp
#pip freeze > requirements.txt
echo "requirements.txt" >> filelist.tmp
echo "update_varnish_cache.py" >> filelist.tmp
echo "build_curl_script.py" >> filelist.tmp
